apiVersion: v1
kind: Secret
metadata:
  name: image-cleaner-secret
data:
  username: <username>
  password: <password>
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: imagecleaner
spec:
  schedule: "0 0 * */2 *" ## every 2 months
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: imagecleaner
            env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: image-cleaner-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: image-cleaner-secret
                  key: password
            image: python:3.8
            imagePullPolicy: IfNotPresent
            command: ["/bin/bash", "-c"]
            args: ["pip install requests && python ./src/image_cleaner.py"]
            volumeMounts:
            - mountPath: /src
              name: src
          restartPolicy: OnFailure
          volumes:
          - name: src
            configMap:
              name: image-cleaner-src