apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: imagecleaner
spec:
  schedule: "0 0 * * *" ## every day 0:00
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets: 
          - name: image-cleaner-secret-ecr
          containers:
          - name: imagecleaner
            image: 257706363616.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/image-cleaner:v1.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - mountPath: /usr/src/conf
              name: conf
          restartPolicy: OnFailure
          volumes:
          - name: conf
            configMap:
              name: image-cleaner-conf
