name: "branch tagging"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'input image tag `vx.y`'
        required: true
        
jobs:
  release-on-push:   
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
          
      - name: Create a GitHub release 
        uses: actions/create-release@v1 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with: 
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.tag }}
          body: Create New release & tag for docker image push
      
