name: build-push-docker-image

on:
  create:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Tag Version
      id: tag_version
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_IMAGE_CLEANER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_IMAGE_CLEANER_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.DEV_IMAGE_CLEANER_AWS_ECR_REPO_NAME }}

    - name: Build and push (ECR)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DEV_IMAGE_CLEANER_AWS_ECR_REPO_NAME }}:${{ steps.tag_version.outputs.tag }}
