name: build-push-docker-image

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Tag Version
      id: tag_version
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_IMAGE_CLEANER_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_IMAGE_CLEANER_AWS_ECR_REPO_NAME }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Image to Amazon ECR
      id: build-push-app-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.DEV_IMAGE_CLEANER_AWS_SECRET_ACCESS_KEY }}
        IMAGE_TAG: ${{ steps.tag_version.outputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
